int _putchar(char c);
void *malloc_checked(unsigned int b);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
int *array_range(int min, int max);
void *_realloc(void *ptr, unsigned int old_size, unsigned int new_size);
int calculate_length(char *s);
char *array(int size);
char *loop_aroundZero(char *str);
int convert_to_digit(char c);
void multiplication(char *res, char *m, int digit, int zero);
void addition(char *fr, char *nr, int nl);
